### ISSUE TITLE
支持与Xinference对接吗

### ISSUE THREAD

**Issue by lordk911** [allwefantasy/byzer-llm#37]
模型已经通过[Xinference](https://inference.readthedocs.io/en/latest/)部署并提供api服务，byzer-llm 能兼容吗？主要想用auto-coder，好像只支持byzer-llm作为模型提供方。

**Comment by allwefantasy** [comment]
Xinference 支持标准额 openAI 格式，所以 byzerllm 是可以支持的。参考我们的ollama的支持示例。
